DROP TABLE BOARD_USERS CASCADE CONSTRAINTS;
PURGE RECYCLEBIN;

CREATE TABLE BOARD_USERS (
  USER_ID      VARCHAR2(50) PRIMARY KEY,             -- 사용자 ID (PK)
  USER_PW      VARCHAR2(100) NOT NULL,               -- 비밀번호
  USER_NAME    VARCHAR2(50) NOT NULL,                -- 이름
  USER_EMAIL   VARCHAR2(100),                        -- 이메일
  USER_BIRTH   DATE NOT NULL,                        -- 생년월일
  CREATED_AT   DATE DEFAULT TRUNC(SYSDATE),          -- 가입일
  PROFILE_IMG  VARCHAR2(200)						 -- 프로필 이미지 
);

-- 더미 사용자 10명 INSERT
INSERT INTO BOARD_USERS (USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_BIRTH, PROFILE_IMG)
VALUES ('user01', '1234', '일지매', 'test01@naver.com', TO_DATE('2000-01-01', 'YYYY-MM-DD'), 'default.png');

INSERT INTO BOARD_USERS (USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_BIRTH, PROFILE_IMG)
VALUES ('user02', '1234', '이순신', 'test02@naver.com', TO_DATE('2000-01-02', 'YYYY-MM-DD'), 'default.png');

INSERT INTO BOARD_USERS (USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_BIRTH, PROFILE_IMG)
VALUES ('user03', '1234', '강감찬', 'test03@naver.com', TO_DATE('2000-01-03', 'YYYY-MM-DD'), 'default.png');

INSERT INTO BOARD_USERS (USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_BIRTH, PROFILE_IMG)
VALUES ('user04', '1234', '유관순', 'test04@naver.com', TO_DATE('2000-01-04', 'YYYY-MM-DD'), 'default.png');

INSERT INTO BOARD_USERS (USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_BIRTH, PROFILE_IMG)
VALUES ('user05', '1234', '김유신', 'test05@naver.com', TO_DATE('2000-01-05', 'YYYY-MM-DD'), 'default.png');

INSERT INTO BOARD_USERS (USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_BIRTH, PROFILE_IMG)
VALUES ('user06', '1234', '신사임당', 'test06@naver.com', TO_DATE('2000-01-06', 'YYYY-MM-DD'), 'default.png');

INSERT INTO BOARD_USERS (USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_BIRTH, PROFILE_IMG)
VALUES ('user07', '1234', '안중근', 'test07@naver.com', TO_DATE('2000-01-07', 'YYYY-MM-DD'), 'default.png');

INSERT INTO BOARD_USERS (USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_BIRTH, PROFILE_IMG)
VALUES ('user08', '1234', '장영실', 'test08@naver.com', TO_DATE('2000-01-08', 'YYYY-MM-DD'), 'default.png');

INSERT INTO BOARD_USERS (USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_BIRTH, PROFILE_IMG)
VALUES ('user09', '1234', '정약용', 'test09@naver.com', TO_DATE('2000-01-09', 'YYYY-MM-DD'), 'default.png');

INSERT INTO BOARD_USERS (USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_BIRTH, PROFILE_IMG)
VALUES ('user10', '1234', '김구', 'test10@naver.com', TO_DATE('2000-01-10', 'YYYY-MM-DD'), 'default.png');

COMMIT;